import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Provider } from "@/components/ui/provider";
import { poppins } from "./ui/fonts";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link
          rel="icon"
          type="image/png"
          href="/img/icon/logo.png"
          sizes="96x96"
        />
        {/* <link rel="icon" type="image/svg+xml" href="/favicon.svg" /> */}
        <link rel="shortcut icon" href="/img/icon/logo.png" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/img/icon/logo.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
      </head>
      <body
        // className={`${roboto.className} ${geistSans.variable} ${geistMono.variable} antialiased`}
        className={`${poppins.className} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
